### ISSUE TITLE
Ability to disable i18n routng for some routes

### ISSUE THREAD

**Issue by umpirsky** [umpirsky/UmpirskyI18nRoutingBundle#2]
```yaml
blog_list:
    path: /blog
    options: { i18n: false }
```
