### ISSUE TITLE
The readme should be more clear about the different with other i18n routing bundles

### ISSUE THREAD

**Issue by stof** [umpirsky/UmpirskyI18nRoutingBundle#21]
The readme says this bundle got inspiration from both BeSimple and JMS i18n routing bundles.
But the feature set does not actually reflect this.

Both BeSimple and JMS bundles are actually about translating the URL itself (so that you have `/en/about` and `/fr/a-propos`).

This bundle is only about adding a locale prefix on all routes. 

The readme makes a clear point about making i18n routing faster. But the way to achieve it is to actually not do i18n. So comparison is not fair

**Comment by stof** [comment]
Btw, a clear proof that this bundle adds much less features: the case of the `prefix` strategy does not need the bundle at all. Here is how to achieve it in pure Symfony (with the drawback of having to split non-i18n routes and i18n routes in separate files instead of putting them together and using the option to distinguish them):

```yaml
# routing.yml
i18n_routes:
    resource: i18n_routing.yml
    prefix: '/{_locale}'
    default:
        # Use a parameter like '%umpirsky_i18n_routing.default_locale%' for DI configuration
        _locale: en
    requirements:
        # You can use a parameter here to if you prefer to main the list of locales elsewhere
        _locale: en|fr|de

non_i18n_routes:
    resource: other_routing.yml
```
